import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export function ChatHeader({ title, subtitle, avatar, statusDotColor, actions, onVideoCall, onAudioCall, onToggleInfo, isInfoVisible, activeCall, onJoinCall, }) {
    const handleJoinCall = () => {
        if (activeCall && onJoinCall) {
            onJoinCall(activeCall.id, activeCall.callType, activeCall.livekitRoomName);
        }
    };
    return (_jsxs("div", { className: "chat-header-content", children: [_jsxs("div", { className: "chat-header-left", children: [avatar ? (_jsx("img", { src: avatar, alt: title, className: "chat-header-avatar" })) : (_jsx("div", { className: "chat-header-avatar chat-header-avatar--fallback", children: title.slice(0, 1).toUpperCase() })), _jsxs("div", { className: "chat-header-text", children: [_jsx("div", { className: "chat-header-title", children: title }), subtitle ? (_jsxs("div", { className: "chat-header-subtitle", children: [statusDotColor ? (_jsx("span", { className: "chat-header-status-dot", style: { backgroundColor: statusDotColor } })) : null, subtitle] })) : null] })] }), activeCall && (_jsxs("div", { className: "chat-header-active-call", children: [_jsxs("div", { className: "chat-header-active-call-indicator", children: [_jsx("span", { className: "chat-header-active-call-pulse" }), _jsxs("span", { className: "chat-header-active-call-text", children: [activeCall.type === 'video' ? '📹' : '📞', " Cu\u1ED9c g\u1ECDi \u0111ang di\u1EC5n ra"] })] }), _jsx("button", { className: "chat-header-join-call-btn", onClick: handleJoinCall, type: "button", children: "Tham gia" })] })), _jsxs("div", { className: "chat-header-actions", children: [!activeCall && onVideoCall && (_jsx("button", { className: "chat-header-action-button", onClick: onVideoCall, title: "G\u1ECDi video", type: "button", children: "\uD83D\uDCF9" })), !activeCall && onAudioCall && (_jsx("button", { className: "chat-header-action-button", onClick: onAudioCall, title: "G\u1ECDi tho\u1EA1i", type: "button", children: "\uD83D\uDCDE" })), onToggleInfo && (_jsx("button", { className: "chat-header-action-button", onClick: onToggleInfo, title: isInfoVisible ? 'Ẩn thông tin đoạn chat' : 'Hiện thông tin đoạn chat', type: "button", children: "\u2139\uFE0F" })), actions] })] }));
}
