export declare const checkWebRTCSupport: () => {
    supported: boolean;
    error?: string;
};
export declare class WebRTCService {
    private peerConnection;
    private localStream;
    private remoteStream;
    private socket;
    private callId;
    private targetUserId;
    private pendingIceCandidates;
    private localIceQueue;
    onRemoteStream: ((stream: any) => void) | null;
    private renegotiationScheduled;
    private icePhase;
    private lastLocalAnswer;
    private iceErrorCount;
    private lastIceErrorTs;
    private answering;
    private currentFacingMode;
    private isSpeakerOn;
    private currentFilter;
    private filterCanvas;
    private filterContext;
    private filterVideoElement;
    private filterStream;
    private screenShareStream;
    private isScreenSharing;
    private getPreferredIceServers;
    constructor(callId: string, targetUserId: string, socket: any);
    updateSocket(socket: any): void;
    updateTargetUser(targetUserId: string): void;
    initializeCall(): Promise<any>;
    private initializeWebCall;
    private initializeMobileCall;
    createOffer(options?: RTCOfferOptions): Promise<void>;
    handleOffer(offer: any): Promise<void>;
    handleAnswer(answer: any): Promise<void>;
    handleIceCandidate(candidate: any): Promise<void>;
    private processPendingIceCandidates;
    private mungeSdpForPhase;
    private buildIceServers;
    private fetchMeteredIceServers;
    private emitIceCandidate;
    getLastLocalAnswer(): any;
    private waitForPeerReady;
    private restartIceWithPhase;
    private handleIceError;
    private attachExistingRemoteTracks;
    getLocalStream(): any;
    getRemoteStream(): any;
    toggleMute(): boolean;
    toggleVideo(): boolean;
    switchCamera(): Promise<boolean>;
    toggleSpeaker(): boolean;
    getCameraPosition(): 'front' | 'back';
    getSpeakerState(): boolean;
    getPeerConnection(): any;
    applyFilter(filterType: 'none' | 'beauty-smooth' | 'beauty-bright' | 'beauty-contrast' | 'fun-blur' | 'fun-vintage' | 'fun-sepia' | 'fun-bw'): Promise<void>;
    private applyBoxBlur;
    getCurrentFilter(): string;
    startScreenShare(): Promise<boolean>;
    stopScreenShare(): Promise<void>;
    getScreenShareState(): boolean;
    endCall(): void;
}
